apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-veloz-config
  namespace: loja-veloz
data:
  ORDERS_URL: http://orders:3001
  PAYMENTS_URL: http://payments:3002
  INVENTORY_URL: http://inventory:3003
