apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loja-veloz
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - gateway.yaml
  - orders.yaml
  - payments.yaml
  - inventory.yaml
