apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: loja-veloz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        runAsNonRoot: true
        fsGroup: 70
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: postgres
          image: postgres:16-alpine

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: loja-veloz-db
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: loja-veloz-db
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: loja-veloz-db
                  key: POSTGRES_PASSWORD

          ports:
            - containerPort: 5432

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 10
            periodSeconds: 10

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: loja-veloz
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432