apiVersion: v1
kind: Secret
metadata:
  name: loja-veloz-db
  namespace: loja-veloz
type: Opaque
stringData:
  POSTGRES_DB: loja_veloz
  POSTGRES_USER: loja
  POSTGRES_PASSWORD: CHANGE_ME
  DATABASE_URL: postgres://loja:CHANGE_ME@postgres:5432/loja_veloz
